### ISSUE TITLE
UpdateRoslynType : Error 'ViewController' : Sequence contains no elements\n   at System.Linq.ThrowHelper.ThrowNoElementsException()

### ISSUE THREAD

**Issue by mcumming** [dotnet/xcsync#130]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Apple platform

macOS

### Framework version

net8.0-*

### Describe the bug

After adding an Outlet to a view controller and syncing the project back to .NET get an exception and the ViewController.designer.cs is not updated

### Expected Behavior

ViewController.designer.cs is updated with correct property for the outlet

### Steps To Reproduce

1. Create a new macos project
2. run generate to create the xcode project
3. In Xcode add a control to the storyboard
4. drag and drop the control as an Outlet to the view controller
5. run sync

### Exceptions (if any)

```UpdateRoslynType : Error 'ViewController' : Sequence contains no elements\n   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at xcsync.Ast.ObjCSyntaxRewriter.Visitor.Write(ObjCPropertyDecl objcProperty) in /_/src/xcsync/Ast/ObjCSyntaxRewriter.cs:line 144
   at xcsync.Ast.ObjCSyntaxRewriter.Visitor.VisitDeclAsync(Decl decl) in /_/src/xcsync/Ast/ObjCSyntaxRewriter.cs:line 89
   at xcsync.AstVisitor.VisitAsync(Cursor cursor) in /_/src/xcsync/Ast/AstVistor.cs:line 21
   at xcsync.AstWalker.WalkAsync(Cursor node, AstVisitor visitor, Func`2 filter) in /_/src/xcsync/Ast/AstWalker.cs:line 20
   at xcsync.AstWalker.WalkAsync(Cursor node, AstVisitor visitor, Func`2 filter) in /_/src/xcsync/Ast/AstWalker.cs:line 24
   at xcsync.Ast.ObjCSyntaxRewriter.WriteAsync(ObjCInterfaceDecl objcType, SyntaxTree syntaxTree) in /_/src/xcsync/Ast/ObjCSyntaxRewriter.cs:line 23
   at xcsync.Projects.XcodeWorkspace.UpdateRoslynType(TypeMapping typeMap, ObjCImplementationDecl objcType) in /_/src/xcsync/Projects/XcodeWorkspace.cs:line 187```

### .NET Version info

.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.7e56472c
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.6
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.300/

.NET workloads installed:
 [macos]
   Installation Source: SDK 8.0.300
   Manifest Version:    14.2.8022/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.macos/14.2.8022/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.61/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-preview.6.24327.7
  Architecture: arm64
  Commit:       static

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.422 [/usr/local/share/dotnet/sdk]
  6.0.425 [/usr/local/share/dotnet/sdk]
  7.0.314 [/usr/local/share/dotnet/sdk]
  7.0.316 [/usr/local/share/dotnet/sdk]
  7.0.317 [/usr/local/share/dotnet/sdk]
  8.0.201 [/usr/local/share/dotnet/sdk]
  8.0.204 [/usr/local/share/dotnet/sdk]
  8.0.300 [/usr/local/share/dotnet/sdk]
  8.0.303 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.30 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.33 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.1.24081.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.1.24080.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/local/share/dotnet]

global.json file:
  /Users/mcumming/repos/xcsynctest/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download


### Anything else?

_No response_

**Comment by mcumming** [comment]
In the `ObjCSyntaxRewriter` this linq call can return null if the ObjC type is not registered in the TypeSystem. 

https://github.com/dotnet/xcsync/blob/main/src/xcsync/Ast/ObjCSyntaxRewriter.cs#L147

**Comment by mcumming** [comment]
Fixed in https://github.com/dotnet/xcsync/pull/140
